
[package]
name = "vrf-oracle"
version = { workspace = true }
edition = { workspace = true }
description = "SolanaVrf Oracle"
authors = { workspace = true }

[dependencies]
clap.workspace = true
solana-vrf-api = { workspace = true}
solana-vrf = { workspace = true}
curve25519-dalek.workspace = true
solana-curve25519.workspace = true
solana-sdk.workspace = true
solana-client.workspace = true
solana-commitment-config.workspace = true
solana-compute-budget-interface.workspace = true
anyhow.workspace = true
tokio.workspace = true
log.workspace = true
env_logger.workspace = true
solana-account-decoder.workspace = true
helius-laserstream.workspace = true
futures-util.workspace = true
async-trait.workspace = true
futures-core.workspace = true
crossbeam-channel.workspace = true
hyper.workspace = true
serde.workspace = true
serde_json.workspace = true
